version: '3'

services:
  cli:
    build: .
    container_name: 'pwsh-spo'
    tty: true
    volumes:
      - ./scripts:/usr/src/scripts
    working_dir: /usr/src/scripts
    env_file:
      - web_variable.env